# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocrapi.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ocrapi.proto',
  package='com.qlisv.grpc.ocr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cocrapi.proto\x12\x12\x63om.qlisv.grpc.ocr\"\x1d\n\nImgRequest\x12\x0f\n\x07imgPath\x18\x01 \x01(\t\"\x1e\n\x0bImgResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t2\xa7\x01\n\x06Ocrapi\x12L\n\x07getText\x12\x1e.com.qlisv.grpc.ocr.ImgRequest\x1a\x1f.com.qlisv.grpc.ocr.ImgResponse\"\x00\x12O\n\ngetImgText\x12\x1e.com.qlisv.grpc.ocr.ImgRequest\x1a\x1f.com.qlisv.grpc.ocr.ImgResponse\"\x00\x62\x06proto3'
)




_IMGREQUEST = _descriptor.Descriptor(
  name='ImgRequest',
  full_name='com.qlisv.grpc.ocr.ImgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='imgPath', full_name='com.qlisv.grpc.ocr.ImgRequest.imgPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=65,
)


_IMGRESPONSE = _descriptor.Descriptor(
  name='ImgResponse',
  full_name='com.qlisv.grpc.ocr.ImgResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='com.qlisv.grpc.ocr.ImgResponse.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['ImgRequest'] = _IMGREQUEST
DESCRIPTOR.message_types_by_name['ImgResponse'] = _IMGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImgRequest = _reflection.GeneratedProtocolMessageType('ImgRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMGREQUEST,
  '__module__' : 'ocrapi_pb2'
  # @@protoc_insertion_point(class_scope:com.qlisv.grpc.ocr.ImgRequest)
  })
_sym_db.RegisterMessage(ImgRequest)

ImgResponse = _reflection.GeneratedProtocolMessageType('ImgResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMGRESPONSE,
  '__module__' : 'ocrapi_pb2'
  # @@protoc_insertion_point(class_scope:com.qlisv.grpc.ocr.ImgResponse)
  })
_sym_db.RegisterMessage(ImgResponse)



_OCRAPI = _descriptor.ServiceDescriptor(
  name='Ocrapi',
  full_name='com.qlisv.grpc.ocr.Ocrapi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=267,
  methods=[
  _descriptor.MethodDescriptor(
    name='getText',
    full_name='com.qlisv.grpc.ocr.Ocrapi.getText',
    index=0,
    containing_service=None,
    input_type=_IMGREQUEST,
    output_type=_IMGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getImgText',
    full_name='com.qlisv.grpc.ocr.Ocrapi.getImgText',
    index=1,
    containing_service=None,
    input_type=_IMGREQUEST,
    output_type=_IMGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCRAPI)

DESCRIPTOR.services_by_name['Ocrapi'] = _OCRAPI

# @@protoc_insertion_point(module_scope)
